recipe: default.v1

language: zh

pipeline:
  - name: "JiebaTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "LanguageModelFeaturizer"
    model_name: "bert"
    model_weights: "hfl/chinese-roberta-wwm-ext-large"
    cache_dir: "./bert_model"
  - name: "EntitySynonymMapper"
  - name: "DIETClassifier"
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_default
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true

