recipe: default.v1
language: zh
pipeline:
  - name: "SpacyNLP"
    "model": "zh_core_web_sm"
    "case_sensitive": False
  - name: "JiebaTokenizer"
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
    "token_pattern": None
  - name: "SpacyFeaturizer"
    "pooling": "mean"
  - name: "RegexFeaturizer"
    "case_sensitive": True
    "use_word_boundaries": True
  - name: "CRFEntityExtractor"
      "BILOU_flag": True
      "features": [
        [ "low", "title", "upper" ],
        [
            "bias",
            "low",
            "prefix5",
            "prefix2",
            "suffix5",
            "suffix3",
            "suffix2",
            "upper",
            "title",
            "digit",
            "pattern",
        ],
        [ "low", "title", "upper" ],
        [ "text_dense_features" ]
      ]
      "max_iterations": 50
      "L1_c": 0.1
      "L2_c": 0.1
      "featurizers": [ ]
      "split_entities_by_comma":
        address: False
        email: True
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
    C: [1, 2, 5, 10, 20, 100]
    kernels: ["linear"]
    "gamma": [0.1]
    "max_cross_validation_folds": 5
    "scoring_function": "f1_weighted"
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_default
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true

