recipe: default.v1

language: zh

pipeline:
  - name: "SpacyNLP"
    model: "zh_core_web_trf"
  - name: "SpacyTokenizer"
    # Flag to check whether to split intents
    "intent_tokenization_flag": False
    # Symbol on which intent should be split
    "intent_split_symbol": "_"
    # Regular expression to detect tokens
    "token_pattern": None
  - name: "SpacyFeaturizer"
    # Specify what pooling operation should be used to calculate the vector of
    # the complete utterance. Available options: 'mean' and 'max'.
    "pooling": "mean"
  - name: "DIETClassifier"
    epochs: 1000

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_default
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true

